server:
  port: 9002
  servlet:
    context-path: /user
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
nacos:
  discovery:
    server-addr: 127.0.0.1:8848

spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848