
server:
  port: 9000
#  servlet:
#    context-path: /gateway
spring:
  application:
    name: gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: first_route
          uri: https://github.com/sunweisheng
          predicates:
            - Path=/test
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234