
server:
  port: 9000
#  servlet:
#    context-path: /gateway
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: order-service-route
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: first_route
          uri: https://github.com/sunweisheng
          predicates:
            - Path=/test


security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234